<a href="https://colab.research.google.com/github/marah-ghanem/AI-ML-tasks/blob/main/Pandas_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Task

1) Load the dataset into a pandas DataFrame and display the first 5 rows.

use opendatasets in case you don't download the data:
don't forget opendatasets it need a kaggle.json file.

In [1]:
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from opendatasets) (4.66.2)
Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (from opendatasets) (1.6.12)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from opendatasets) (8.1.7)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2024.2.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.31.0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.0.7)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (6.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.7)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [2]:
import opendatasets as od

In [3]:
od.download('https://www.kaggle.com/datasets/spscientist/students-performance-in-exams/data')

Dataset URL: https://www.kaggle.com/datasets/spscientist/students-performance-in-exams
Downloading students-performance-in-exams.zip to ./students-performance-in-exams

100%|██████████| 8.70k/8.70k [00:00<00:00, 15.1MB/s]

you can Load the dataset directly if downloded using pandas

In [4]:
# Load the dataset
import pandas as pd
df = pd.read_csv('/content/students-performance-in-exams/StudentsPerformance.csv')

In [5]:
# Display the first 5 rows
df.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

2) How many students are there in the dataset?

In [7]:
# Count the number of rows
df.shape

(1000, 8)

3) What are the unique values in the 'gender' column?

In [8]:
# Get unique values in the 'gender' column
df['gender'].unique()

array(['female', 'male'], dtype=object)

4) What is the average score in math among female students?

In [9]:
# Calculate the average math score among female students
famele=df[df['gender'] == 'female']
math_females=famele['math score'].mean()

In [10]:
math_females

63.633204633204635

5) What is the maximum score in reading among male students?

In [11]:
# Find the maximum reading score among male students
male=df[df['gender'] == 'male']
read_s=male['reading score'].max()

In [12]:
read_s

100

6) Create a new column 'total_score' which sums up the scores of math, reading, and writing for each student.

In [13]:
# Create a new column 'total_score'
#df['total_score']= df[['math score', 'reading score', 'writing score']].sum()
df['total_score']=df['math score']+df['reading score']+df['writing score']

In [14]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229

7) Who scored the highest total marks and what is the score?

In [15]:
# Find the student with the highest total score
highest_score_index = df['total_score'].idxmax()
student_highest_score = df.loc[highest_score_index]
print(student_highest_score)

gender                                    female
race/ethnicity                           group E
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                   100
reading score                                100
writing score                                100
total_score                                  300
Name: 458, dtype: object

8) Calculate the mean, median, and standard deviation of scores in writing.

In [16]:
# Calculate mean, median, and standard deviation of writing scores
df['writing score'].mean()

68.054

In [17]:
df['writing score'].median()

69.0

In [18]:
df['writing score'].std()

15.19565701086965

.describe it easier way to get the info!

In [19]:
df['writing score'].describe()

count    1000.000000
mean       68.054000
std        15.195657
min        10.000000
25%        57.750000
50%        69.000000
75%        79.000000
max       100.000000
Name: writing score, dtype: float64

9) How many students have scored above 90 in all subjects?

In [20]:
# Count the number of students who scored above 90 in all subjects
num_student_90=len(df[(df['math score']>90)&(df['reading score']>90)&(df['writing score']>90)])
print(num_student_90)

23

10)Create a new column 'pass_status' which contains 'Pass' if the student's total score is greater than or equal to 150, otherwise 'Fail'.

.apply(lambda x: 'Pass' if x >= 150 else 'Fail'):
This applies a function to each element in the 'total_score' column.
The function is defined using a **lambda function**:
lambda x: 'Pass' if x >= 150 else 'Fail':
This defines a lambda function that takes one argument x (which represents each value in the 'total_score' column).
If the value x is greater than or equal to 150 (x >= 150), it returns 'Pass'.
Otherwise, it returns 'Fail'.

In [21]:
# Create a new column 'pass_status'
df['pass_status']=df['total_score'].apply(lambda x:'pass' if x>=150 else 'Fail')

In [22]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score,pass_status
0,female,group B,bachelor's degree,standard,none,72,72,74,218,pass
1,female,group C,some college,standard,completed,69,90,88,247,pass
2,female,group B,master's degree,standard,none,90,95,93,278,pass
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,Fail
4,male,group C,some college,standard,none,76,78,75,229,pass

11) How many null values are there in each column of the dataset?

In [23]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score,pass_status
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False

# Dataset

https://www.kaggle.com/datasets/spscientist/students-performance-in-exams